name: "Deploy Periphery"

env:
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}
  RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "sepolia"
        description: "Chain name as defined in the Foundry config."
        required: false


jobs:
  deploy-periphery:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy all Sablier V2 Periphery contracts"
        run: >-
          forge script script/DeployPeriphery.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run()"
          --verify
          -vvvv

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Done" >> $GITHUB_STEP_SUMMARY
